language: node_js

node_js:
- '8'
- '10'

services:
- mongodb

sudo: false

cache:
  directories:
  - 'node_modules'

before_script:
- npm install
- npm install -g coveralls lerna
- lerna bootstrap --no-package-lock --no-ci
- sleep 2 # thanks mongo

script:
- ./node_modules/.bin/jest --coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
